---
all:
  children:
    k8s_nodes:
      hosts:
        staging-node-01:
          ansible_host: 10.0.2.10
        staging-node-02:
          ansible_host: 10.0.2.11
        staging-node-03:
          ansible_host: 10.0.2.12
      vars:
        environment: staging
        kubernetes_cluster_name: staging-k8s-cluster

    k8s_masters:
      hosts:
        staging-master-01:
          ansible_host: 10.0.2.5
      vars:
        environment: staging
        node_role: master

  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/staging-k8s.pem
    ansible_python_interpreter: /usr/bin/python3
