---
all:
  children:
    k8s_nodes:
      hosts:
        dev-node-01:
          ansible_host: 10.0.1.10
        dev-node-02:
          ansible_host: 10.0.1.11
        dev-node-03:
          ansible_host: 10.0.1.12
      vars:
        environment: dev
        kubernetes_cluster_name: dev-k8s-cluster

    k8s_masters:
      hosts:
        dev-master-01:
          ansible_host: 10.0.1.5
      vars:
        environment: dev
        node_role: master

  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/dev-k8s.pem
    ansible_python_interpreter: /usr/bin/python3
