---
all:
  children:
    k8s_nodes:
      hosts:
        prod-node-01:
          ansible_host: 10.0.3.10
        prod-node-02:
          ansible_host: 10.0.3.11
        prod-node-03:
          ansible_host: 10.0.3.12
        prod-node-04:
          ansible_host: 10.0.3.13
        prod-node-05:
          ansible_host: 10.0.3.14
        prod-node-06:
          ansible_host: 10.0.3.15
      vars:
        environment: production
        kubernetes_cluster_name: prod-k8s-cluster

    k8s_masters:
      hosts:
        prod-master-01:
          ansible_host: 10.0.3.5
        prod-master-02:
          ansible_host: 10.0.3.6
        prod-master-03:
          ansible_host: 10.0.3.7
      vars:
        environment: production
        node_role: master

  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/prod-k8s.pem
    ansible_python_interpreter: /usr/bin/python3
